---
# this is used for local development and testing
version: "3.0"
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    #image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - META_TITLE=Techno Tim
      - META_DESCRIPTION=Techno Tim Link page
      - META_AUTHOR=Techno Tim
      - META_KEYWORDS=HomeLab, CSS, HTML, Engineering
      - LANG=en
      - META_INDEX_STATUS=all
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - AVATAR_ALT=Techno Tim Profile Pic
      - NAME=TechnoTim
      - BIO=Hey! Just a place where you can connect with me!
      - FOOTER=Thanks for stopping by!
      - GITHUB=https://github.com/timothystewart6
      - TWITTER=https://twitter.com/TechnoTimLive
      - INSTAGRAM=https://www.instagram.com/techno.tim
      - YOUTUBE=https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
      - TWITCH=https://www.twitch.tv/technotim/
      - DISCORD=https://l.technotim.live/discord
      - TIKTOK=https://www.tiktok.com/@technotim
      - KIT=https://kit.co/TechnoTim
      - FACEBOOK=https://facebook.com
      - FACEBOOK_MESSENGER=https://facebook.com
      - LINKED_IN=https://linkedin.com
      - PRODUCT_HUNT=https://www.producthunt.com/
      - SNAPCHAT=https://www.snapchat.com/
      - SPOTIFY=https://www.spotify.com/
      - REDDIT=https://www.reddit.com/
      - MEDIUM=https://medium.com
      - PINTEREST=https://www.pinterest.com/
      - EMAIL=you@example.com
      - EMAIL_TEXT=Email Me!
      - EMAIL_ALT=you@example.com
      - EMAIL_ALT_TEXT=Email me!
      - SOUND_CLOUD=https://soundcloud.com
      - FIGMA=https://figma.com
      - TELEGRAM=https://telegram.org/
      - TUMBLR=https://www.tumblr.com/
      - STEAM=https://steamcommunity.com/
      - VIMEO=https://vimeo.com/
      - WORDPRESS=https://wordpress.com/
      - GOODREADS=https://www.goodreads.com/
      - SKOOB=https://www.skoob.com.br/
      - LETTERBOXD=https://letterboxd.com/
      - MASTODON=https://mastodon.social/
      - MICRO_BLOG=https://micro.blog/
      - WHATSAPP=https://www.whatsapp.com/
      - STRAVA=https://www.strava.com/
      - BLUESKY=https://bsky.app/profile/bsky.app
      - BUYMEACOFFEE=https://www.buymeacoffee.com/
      - GITLAB=https://www.gitlab.com/
      - PATREON=https://www.patreon.com/technotim
      - DEVTO=https://dev.to/
      - UMAMI_WEBSITE_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - UMAMI_APP_URL=https://your-umami-app.com
      - UMAMI_SCRIPT_NAME=script.js
      - BUTTON_ORDER=YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,DISCORD,FACEBOOK,TIKTOK,KIT,PATREON
      - PAYPAL=https://www.paypal.me/user
      - SLACK=https://slack.com/
      - STACKOVERFLOW=https://stackoverflow.com/
      - LASTFM=https://last.fm/
      - GITEA=https://gitea.io/
      - POLYWORK=https://www.polywork.com/
      - SIGNAL=https://signal.org/
      - UNTAPPD=https://untappd.com/
      - BUTTON_TARGET=_blank
      - INSTANTGAMING=https://www.instant-gaming.com/
      - GHOST=https://ghost.org/
      - TRAKT=https://trakt.tv
      - CASHAPP=https://cash.app/
      - TEESPRING=https://teespring.com/
      - XING=https://www.xing.com/en
      - KEYBASE=https://keybase.io/
      - ONLYFANS=https://onlyfans.com/
      - SESSION=https://getsession.org/
      - THREEMA=https://threema.ch/en/
      - STREAMLABS=https://streamlabs.com/
      - PRIVATEBIN=https://privatebin.net/
      - AMAZON_AFFILIATE=https://affiliate-program.amazon.co.uk/
      - AMAZON_WISHLIST=https://www.amazon.co.uk/b?node=22758010031
      - APPLE_MUSIC=https://www.apple.com/uk/apple-music/
      - YOUTUBE_MUSIC=https://music.youtube.com/playlist?list=
      - VENMO=https://venmo.com/
      - STATUS=https://status.im/
      - MATRIX=https://matrix.to/
      - ANILIST=https://anilist.co/
      - GITBUCKET=https://gitbucket.github.io/
      - SHAZAM=https://www.shazam.com/myshazam
      - TPDB=https://theposterdb.com/
      - FLICKR=https://www.flickr.com/
      - OSU=https://osu.ppy.sh/users/
      - LINE=https://line.me/en/
      - KAKAOTALK=https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=ko
      - DESIGNBYHUMANS=https://www.designbyhumans.com/
      - DOCKERHUB=https://hub.docker.com/
      - VERO=https://vero.co/
      - MYANIMELIST=https://myanimelist.net/
      - OG_SITE_NAME=Techno Tim Live (OG)
      - OG_TITLE=Techno Tim (OG)
      - OG_DESCRIPTION=Techno Tim Link page (OG)
      - OG_URL=https://technotim.live/
      - OG_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - TWITTER_CARD=summary_large_image
      - TWITTER_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - TWITTER_SITE=@TechnoTimLive
      - TWITTER_CREATOR=@TechnoTimLive
      - SHARE=https://technotim.live
      - FIVEHUNDREDPX=https://500px.com/
      - PRINTABLES=https://www.printables.com
      - SERIALIZD=https://www.serializd.com/
      - LEMMY=https://join-lemmy.org
      - PIXELFED=https://pixelfed.org/
      - VRCHAT=https://vrchat.com
      - X=https://x.com
      - CODEWARS=https://www.codewars.com
      - APPLE_PODCASTS=https://podcasts.apple.com/de/podcast/NAME/id000000000
      - GOOGLE_PODCASTS=https://podcasts.google.com/feed/XYZ
      - POCKET_CASTS=https://pca.st/XYZ
      - OVERCAST=https://overcast.fm/itunes00000000
      - RSS=https://example.com/rss
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
